#!/usr/bin/env bash
set -e
# set -x


if [ "$#" -ne 1 ]; then
	echo "usage error: provide config as parameter"
	exit 1
fi


if [ -f watch_extra_dirs.sh ]; then
	source watch_extra_dirs.sh
fi

watchmedo auto-restart \
	--recursive \
	--patterns '*.py;*.ini' \
	--directory . \
	$watch_extra_dirs \
	--ignore-patterns venv \
	python -- src/mistress_stat/stat_server.py "$@"
